name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-check:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Qt6 
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.10.*'
          arch: ${{ matrix.os == 'macos-latest' && 'clang_64' || (matrix.os == 'windows-latest' && 'win64_msvc2022_64' || 'linux_gcc_64') }}
          modules: 'qtmultimedia qtshadertools'

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build only (no packaging)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release